### ISSUE TITLE
Some errors and broken mod news

### ISSUE THREAD

**Issue by DingoDjango** [UnlimitedHugs/RimworldHugsLib#1]
[output_log.txt](https://github.com/UnlimitedHugs/RimworldHugsLib/files/549462/output_log.txt)

I tried playing around with the Hand Me That Brick DLL we made. I also deleted HugsLib from my appdata folder to test clean slate scenarios (e.g. if a user just updated without another HugsLib mod).

Apparently at some point parts of HugsLib break somewhat. For example, I can no longer click "show all mod news" in the Mod Settings menu and I got some errors via console (visible in the log).

In this log HMTB is disabled but AllowTool is enabled.

**Comment by DingoDjango** [comment]
Did some further testing. I used the "-savedatafolder=PATHTOFOLDER" command to launch a clean RimWorld, no Steam and no previous save/config/modlist. Only enabled Hand Me That Brick this time.

I think what happens is it tries to load mod update news but then throws an error.

**Comment by UnlimitedHugs** [comment]
Oh wow. Turns out, the whole update news feature wouldn't work if Dev mode was off.  Thank you for reporting this.
I updated the dll, so make sure to grab the new one for HMTB.

**Comment by DingoDjango** [comment]
Excellent! Thanks.
