### ISSUE TITLE
Hang-Crash On World Load-Cross Mod Conflicts

### ISSUE THREAD

**Issue by Anarcraft** [UnlimitedHugs/RimworldHugsLib#10]
I submitted a bug report to the Psychology Mod developer and per their suggestion I am now submitting the issue here.  Psychology and HugsLib WILL WORK TOGETHER, I cannot reproduce the issue.  To reproduce I have to have other mods enabled for it to happen but I don't know which ones (I have a crapload of mods enabled).  If I had to guess maybe it's ones that add custom factions?

See the details/log in my original post here.
http://steamcommunity.com/workshop/filedetails/discussion/747313773/154644928867855655/

HugsLib and Psychology were both recently updated and this recently became an issue. (other recent updates include Colonist Bar KF and Static Quality Plus)

**Comment by HK47196** [comment]
I'm experiencing the same issue on Linux. It only happens with the 64bit executable, 32 bit one (weirdly) works just fine.

Happens only with HugsLib and Psychology mod enabled, so it has to be an issue with Psychology(or what part of HugsLib it uses,) I assume.

This only started happening recently, I think it may be related to the fallback attribute feature added in 2.2.0? Seems Psychology also updated to use it.

**Comment by Anarcraft** [comment]
I can confirm that running in 32-bit mode works.

**Comment by Collserra** [comment]
I have also had crashes while running HugsLib, Psychology, and faction-adding mods.
I can also confirm that running 32-bit mode could serve as a temporary workaround.

**Comment by UnlimitedHugs** [comment]
This is too broad of a problem to diagnose. I would appreciate if you could narrow down the issue, so that it can be reproduced consistently.
Another problem is that I don't have a Linux machine or install to test things on. I guess I could try to fire up a VM, but it's unclear how reliable of a testing environment that would be.

**Comment by autonia** [comment]
I have the same issue and I'm on a Mac.

Here's a link to the bug discussion on Steam:
http://steamcommunity.com/workshop/filedetails/discussion/747313773/154644928867855655/

**Comment by UnlimitedHugs** [comment]
I would try running the game with the 2.2.1, 2.2.0 and 2.1.6 versions of the lib- it would be interesting to know at which point the issue got introduced.

**Comment by HK47196** [comment]
It wouldn't load with 2.1.6 when I tried, 2.2.0 produced the same error as 2.2.2.

**Comment by UnlimitedHugs** [comment]
I've also got a new version on the dev branch. No release for that one yet, but you could try replacing your dll with this one: https://github.com/UnlimitedHugs/RimworldHugsLib/blob/94cd59367c266e54c1de725409ee44474989362c/Mods/HugsLib/Assemblies/HugsLib.dll

**Comment by Anarcraft** [comment]
Tried the new DLL and it now generates my test world with the "zack" seed!  However when I tried to open my older save file it got it's generic error about being unable to load it ("save file had these mods, we are running these mods" message).  Do you want the log file for this?  I wanted to try a new save file for my "zack" world but the in game interface was too broken to even save, I had to force quit.

**Comment by UnlimitedHugs** [comment]
I'm relieved to hear that at least the lib managed to load.
There is still work and testing to be done on that new version, so the other issues are not entirely surprising.
The log file with the new errors would be helpful.

**Comment by Anarcraft** [comment]
http://pastebin.com/V2jVQNNK

**Comment by HK47196** [comment]
Just a status update: I'm no longer experiencing this bug, unsure if the others have been but they've been silent.

**Comment by Anarcraft** [comment]
Confirmed that it works now.  I tried just a few days ago and it was still crashing so a very recent update fixed it.  I'll let the dev close this issue as they see fit.

**Comment by UnlimitedHugs** [comment]
Still no idea what was causing it, but I'll just mark this as resolved. I guess it's one of those problems that goes away if you ignore it long enough.
