### ISSUE TITLE
Settings for non-library mods Broken in 1.5

### ISSUE THREAD

**Issue by Kosaro** [UnlimitedHugs/RimworldHugsLib#106]
In a mod that doesn't extend `ModBase`, these two lines of code successfully create a mod setting in 1.4 but not in 1.5.
```
var modSettings = HugsLibController.SettingsManager.GetModSettings("foo", "bar");
var floatSettingHandle = modSettings.GetHandle<float>("FloatSetting", "Float setting", "description");
```

More specifically the issue is that the button to open this mod's settings doesn't appear in rimworld's mod setting menu. The handle is succesfully created and saved values are loaded, but they can't be change since the mod setting UI can't be opened.

**Comment by UnlimitedHugs** [comment]
I appreciate the report. Should be resolved in 11.0.4.
