### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by bukowa** [UnlimitedHugs/RimworldHugsLib#107]
Any chance to get examples folder with some examples of usage?

**Comment by UnlimitedHugs** [comment]
HugsLib is in maintenance mode, so my recommendation is to avoid depending on it when developing new mods. These days the base game in conjunction with Harmony gives you all of the tools needed to make any mod that you can imagine, no 3rd party libraries needed.
Also, feel free to borrow any code from HugsLib if you need it.
