### ISSUE TITLE
using Verse;

### ISSUE THREAD

**Issue by gregebriggs** [UnlimitedHugs/RimworldHugsLib#12]
I am sorry to ask a silly question, but what is Verse? I ask this as visual studio 2015 finds it as an error. I was able to get the Unity Engine directory added to the project, but I can't find anything outside of IBM's email service called Verse. Any help would be greatly appreciated.

**Comment by CrystallineCat** [comment]
Verse is part of RimWorld. It's sort of an engine that sits between RimWorld and Unity. Did you add `Assembly-CSharp.dll` from `RimWorld/RimWorld<Platform>_Data/Managed` as a reference? That file contains both the Verse and RimWorld namespaces.

**Comment by DingoDjango** [comment]
Verse is the namespace Tynan gave to a bunch of RimWorld's classes, instead of having it all be in the RimWorld namespace. Think of it as a developer organising things within the code, it's nothing special inherently.

**Comment by UnlimitedHugs** [comment]
Closing as unrelated to the library.

@gregebriggs The [modding help forum](https://ludeon.com/forums/index.php?board=14.0) is a better place to ask general question about Rimworld modding.
