### ISSUE TITLE
Pawn Rotator

### ISSUE THREAD

**Issue by ghost** [UnlimitedHugs/RimworldHugsLib#19]
The Pawn Rotator was a problem in A16, and a lot of people were banking on it being fixed in A17. Sadly, the one that works is private, and the one that's public just doesn't work, just as before.

This would be a valuable function for HugsLib to include.

**Comment by UnlimitedHugs** [comment]
I will look into it.

**Comment by UnlimitedHugs** [comment]
If you could link me some reading material on the issue, that would make my job easier.
Forum posts, the not-working fix, whatever you have.
