### ISSUE TITLE
Enum Menu Handle does not call SettingsChanged.

### ISSUE THREAD

**Issue by mindryu** [UnlimitedHugs/RimworldHugsLib#3]
It also does not save value.

**Comment by mindryu** [comment]
Outer Variable Trap
Access DrawHandleInputEnum changed value inside lambda.

**Comment by UnlimitedHugs** [comment]
Good catch, thank you.
I will most likely release the next version when A16 comes out, as I don't want to update all of my mods.
If you absolutely need enum settings to work now, I would recommend using SettingHandle.CustomDrawer.

**Comment by UnlimitedHugs** [comment]
Resolved in the 2.0.0 release.
