### ISSUE TITLE
SettingHandle.OnValueChanged in Wiki

### ISSUE THREAD

**Issue by Dimondheart** [UnlimitedHugs/RimworldHugsLib#35]
OnValueChanged appears to be part of SettingHandle according to the wiki, but I cannot seem to find it anywhere at all in the source code. [Section in wiki](https://github.com/UnlimitedHugs/RimworldHugsLib/wiki/Adding-mod-settings#onvaluechanged)
Is this something from a previous version, or what?

**Comment by UnlimitedHugs** [comment]
https://github.com/UnlimitedHugs/RimworldHugsLib/blob/master/Source/Settings/SettingHandle.cs#L89
It's a callback you can set to listen for changes to a specific handle. I can add some example code if it helps.

**Comment by Dimondheart** [comment]
Yah, some example code would be helpful.

**Comment by Dimondheart** [comment]
I must have somehow missed that when looking through the source, my bad.

**Comment by UnlimitedHugs** [comment]
Added the [example code](https://github.com/UnlimitedHugs/RimworldHugsLib/wiki/Adding-Mod-Settings#onvaluechanged).
