### ISSUE TITLE
[B18] Pawns can't finish eating their meals, looping forever until starvation

### ISSUE THREAD

**Issue by frenchiveruti** [UnlimitedHugs/RimworldHugsLib#38]
Hello, I don't know which mod drives the job selection but I assume it has something to do with your mod.

Here's the log:
https://gist.github.com/d54a32a96bb35d8f4deea2fc50d306da
Here's a pic of the issue, the two colonist there can't finish their meals, I wish I could record it but I can't.
![bug eaters](https://user-images.githubusercontent.com/1095997/33187230-1b81d280-d06f-11e7-8109-cc84fb469e71.png)

Here's my modlist:
[ModsConfig.txt](https://github.com/UnlimitedHugs/RimworldHugsLib/files/1500145/ModsConfig.txt)

**Comment by frenchiveruti** [comment]
As a side note: Closing the game and opening the save again solves the issue.

**Comment by UnlimitedHugs** [comment]
HugsLib has no job related code, so it would have to be another mod.
Still, I could take a look at your log- press Ctrl+F12 once you see the errors, and post the link.

**Comment by frenchiveruti** [comment]
I think that's the first link I posted?

**Comment by UnlimitedHugs** [comment]
Right, I missed that.
Looks like one of your mods has created a `Thing` without a `Def`, and the pathfinder is choking on it.
Unfortunately I can't offer any suggestions- I would have to run some code to diagnose this one.
If you can reliably recreate the problem, then starting a new game with half your mods disabled could help narrow down the offender. If the problem does not occur, try with the other half, and so on.

**Comment by frenchiveruti** [comment]
I see, I believe is hospitality because it also happens on trades.  
But also could be one of those new mods hanging around the new version, and poorly implemented ha.
I'll close this as has nothing to do with your ~~mod~~ library.  
Thanks for the Hugs 😄
