### ISSUE TITLE
[Suggestion] ModSync Ninja support

### ISSUE THREAD

**Issue by frenchiveruti** [UnlimitedHugs/RimworldHugsLib#39]
Hi! It would be nice if you made your library join the list 😀 
http://modsync.ninja/
https://ludeon.com/forums/index.php?topic=34443.0

**Comment by UnlimitedHugs** [comment]
ModSync support added in version [5.0.0](https://github.com/UnlimitedHugs/RimworldHugsLib/commit/6b17ff3240178bcf7698fccf1d8305f81947b8bf)

**Comment by frenchiveruti** [comment]
yay!
