### ISSUE TITLE
Suggestion: Add "Restart Game"

### ISSUE THREAD

**Issue by Mehni** [UnlimitedHugs/RimworldHugsLib#41]
Basically this mod: 

https://steamcommunity.com/sharedfiles/filedetails/?id=1221346281

That one prefixes and returns false so it's currently not compatible with HugsLib, but it's a practical thing to have when modding.

**Comment by UnlimitedHugs** [comment]
HugsLib already has a binding that does exactly that. Just assign a key to use it.

**Comment by Mehni** [comment]
Hot diggity. The things people like me could find if only they would bother to read.

Thank you.

**Comment by lilwhitemouse** [comment]
Wait, what?

I didn't see anything your list of features, but I'll go use that now ^.^

Any chance we could have a second version that needs [Ctrl] pressed as well?  Just so a single random keystroke doesn't accidentally restart the game?

**Comment by lilwhitemouse** [comment]
Also, as Mehni said, hot diggity.

**Comment by UnlimitedHugs** [comment]
> Any chance we could have a second version that needs [Ctrl] pressed as well?

Just bind it to the Pause or Scroll lock key. Been a while since I pressed any of those.
