### ISSUE TITLE
Expose AssemblyFileVersion in log

### ISSUE THREAD

**Issue by FluffierThanThou** [UnlimitedHugs/RimworldHugsLib#44]
See FluffierThanThou/Pharmacist#11 for more info on why this matters, although you're probably aware already given the version override you're using yourself.

I've stopped updating AssemblyVersion for non-major releases to make life easier for others referencing my dll's, but unfortunately that means that my dlls are now also reported with the wrong (or at least incomplete) version information in hugslib logs. I'd rather not add a version override file, given that there's a perfectly reasonable alternative (AssemblyFileVersion) available.

It would be nice if HugsLib could either report whichever version is higher, or just report both.

**Comment by UnlimitedHugs** [comment]
TIL about `AssemblyFileVersion`.
I'll implement that sometime soon- if it's not urgent.

**Comment by FluffierThanThou** [comment]
no rush, just a QoL thing for me and possible other modders that do this.

**Comment by alextd** [comment]
So, the root problem here is that people are updating AssemblyVersion. Once HugsLib gets this update, the update news should make people aware to use AssemblyFileVersion for little version updates, TL;DR  from https://support.microsoft.com/en-us/help/556041

Now, I may be the only one adding other mod's DLL references in my mods for compatibility purposes so who knows if this is a real problem - but if anyone else is, a change to AssemblyVersion often means compatibility is silently disabled and a re-build mysteriously fixes it.

**Comment by UnlimitedHugs** [comment]
Update news are for advertising new mod features to players- if used for other things, the player will likely click the X next time they see the window, because they will associate it with being bored.
You might simply ask the modder in question to switch to `AssemblyFileVersion` if your mod is has a dependency on their assembly.

**Comment by FluffierThanThou** [comment]
Yeah, I agree this is not something that warrants a ping to all players.
It's going to be much more efficient to just message the creator of the mod.

That said, i would still like hugslib to report both versions, or the
higher of the two.

**Comment by alextd** [comment]
Oh, I wasn't talking about ingame "mod update news"

I was saying more like HugsLib documentation should mention it. People have been saying they update AssemblyVersion because HugsLib uses it, shows it in the logs. I don't know where that is exactly, but that should be AssemblyFileVersion as well.

**Comment by FluffierThanThou** [comment]
Yeah, that's what this issue is about 😎

**Comment by UnlimitedHugs** [comment]
Done and done. [Release](https://github.com/UnlimitedHugs/RimworldHugsLib/releases/tag/v6.1.0) and [update notes](https://ludeon.com/forums/index.php?topic=28066.msg443051#msg443051).

**Comment by FluffierThanThou** [comment]
thank you!

**Comment by alextd** [comment]
Great this is a good step to mod compatibility,

(next step is now to teach everyone how to do transpilers)
