### ISSUE TITLE
"Restart the game and reload most recent game" button to quickstart menu?

### ISSUE THREAD

**Issue by lilwhitemouse** [UnlimitedHugs/RimworldHugsLib#48]
Another button I would love is "Restart the game and load the most recent save."

I am hoping that this would be easy to add to the quickstart functionality.  The quickstarter isn't quite useful to me as it, as my debug save game names often change.

Thanks,

**Comment by UnlimitedHugs** [comment]
The "most recent save" is a workable idea. I'll see if I can include that in a future update.
As for the restart, we have a key biding for that.
