### ISSUE TITLE
Add support for a textbox using TextAreaScrollable

### ISSUE THREAD

**Issue by SineSwiper** [UnlimitedHugs/RimworldHugsLib#53]
The string widget, via `DrawHandleInputText`, isn't large enough to reasonable hold a string larger than 30 characters or so.  I rolled my own CustomDrawer for a few settings I had, but it might be more practical to create some sort of `DrawHandleInputTextbox` method in Dialog_ModSettings.cs.

**Comment by UnlimitedHugs** [comment]
The best approach is to trim down your label to just a few words, even if they don't fully explain what the setting does. For the explanation, use the description parameter.

If you still need a long label:
- The label will automatically reduce its text size if it does not fit. This gives you two lines of text to work with.
- Use [CustomDrawerFullWidth](https://github.com/UnlimitedHugs/RimworldHugsLib/wiki/Adding-mod-settings#customdrawerfullwidth) for complete control over handle drawing.
