### ISSUE TITLE
HugsLib & Replace Stuff

### ISSUE THREAD

**Issue by KazTheMercenary** [UnlimitedHugs/RimworldHugsLib#59]
Hey guys.  ^_^;;  Umm... I'm not terribly familiar with flagging conflicts on GitHub, so fingers crossed that this is the right spot for that.

For some really odd reason, (EDIT) Replace Stuff seems to HAVE to be loaded above HugsLib, or it throws several errors and... no joke... destroys the build menu.  All of it.  Can't build, area, blueprint ~anything.

I have zero idea the how-and-why.  It was just SUCH an odd thing that I thought I'd draw your attention to it.  If you need specific error information, you can certainly poke at their Workshop page, or I can provide any logs you might need.

Could be nothing.  Could be important.

I'm not qualified to tell the difference!  ^_^;;

Thanks in advance.

**Comment by UnlimitedHugs** [comment]
Is this a Rimworld 1.0 or 1.1 issue? Allow Tool for 1.1 is not released yet, just as a heads-up.
Also, please include a Ctrl+F12 log with your reports.

**Comment by KazTheMercenary** [comment]
My apologies, I mis-typed.  -__-  I MEANT to say 'Replace Stuff', but I was also looking up your Allow Tool / Haul Urgently, and got mixed up.

Version 1.1 issue.

It ALSO appears that you fixed it with your update from 6.2.0 to 6.2.1, which I noticed right after I posted.

I let folks now to manually update to 6.2.1... but I can still downgrade and throw you the F12 if you would like.

**Comment by UnlimitedHugs** [comment]
If it works, it works. No need to investigate further.
Also, manual updates are only necessary if you are playing the non-Steam version, since 6.2.1 is live on Steam.
