### ISSUE TITLE
Pressing console hotkey always opens console

### ISSUE THREAD

**Issue by DingoDjango** [UnlimitedHugs/RimworldHugsLib#6]
When using HugsLib on A16 stable, pressing the console hotkey opens the console even if it is already open.

You have to manually press X to exit the console, instead of being able to toggle it with the hotkey.

**Comment by UnlimitedHugs** [comment]
Yeah, there's also another issue- repeated exceptions will keep re-opening the log window, causing it to be replaced each time.
Still thinking about how to approach these without getting into detour territory.

**Comment by UnlimitedHugs** [comment]
Fixed in 2.3.0.
