### ISSUE TITLE
UpdateFeatureDef "Name" must be globally unique.

### ISSUE THREAD

**Issue by CodeOptimist** [UnlimitedHugs/RimworldHugsLib#61]
Maybe it's something I'm doing, but I just discovered that "UpdateFeatureBase" from the following:
`<HugsLib.UpdateFeatureDef Abstract="true" Name="UpdateFeatureBase">`
threw an error as soon as I updated a second mod to 1.1, because they both used it:
![image](https://user-images.githubusercontent.com/52485/77079260-57bd9880-69bd-11ea-8c9c-d815bd03e306.png)
I changed them to prefix my packageIds.
Just another departure from 1.0 I thought worth mentioning... maybe for the documentation? I assume this isn't a bug with HugsLib but just the way 1.1 does things.

**Comment by UnlimitedHugs** [comment]
Fixed in 7.1.1.
