### ISSUE TITLE
error on loading savegame

### ISSUE THREAD

**Issue by Yaksinikos** [UnlimitedHugs/RimworldHugsLib#63]
[GistLog](https://gist.github.com/Translator5/d89c452c9ffb17887c37a28de4afab39)

**Comment by UnlimitedHugs** [comment]
Not enough info to go on, but clearly not a HugsLib issue.
All I can tell you is one of the nobles in your save file has a title that was issued by an unknown faction. This should not be possible, and thus the error.
You could try some manual editing to salvage the save file if you care enough.
