### ISSUE TITLE
Request: PatchOperationFindModByPackageId

### ISSUE THREAD

**Issue by Fumblesneeze** [UnlimitedHugs/RimworldHugsLib#64]
Hi,

just a small request, since it's still not in the base game and a huge oversight imo, could you add a 
```PatchOperationFindModByPackageId```
That works similarly to PatchOperationFindMod but instead of looking at the ```<name>``` node, it looks for the ```<packageId>``` node.

**Comment by UnlimitedHugs** [comment]
Heyo. I'd say that's supremely useful. but why not just add that to your own mod assembly?
Seems like a straightforward addition. Unless, of course, your mod is purely XML-based.

**Comment by Fumblesneeze** [comment]
No problem with that. Just, as I said, I believe that should be in the base game, so I think it would be good if a common library like HugsLib would provide it.

**Comment by UnlimitedHugs** [comment]
I'll pass.
My general policy is to only add and maintain things I need for my own mods- and even then, I likely would not make it publicly available. There is a maintenance overhead for these things, as you know.

Take heart, though- I'm fairly sure it will soon make its way into the base game.
