### ISSUE TITLE
Don't default to quick start when using quick start.

### ISSUE THREAD

**Issue by FluffierThanThou** [UnlimitedHugs/RimworldHugsLib#65]
Whenever you use one of the quickstart options manually (e.g. 'generate now'), HugsLib turns on the option to use that quickstart mode by default on game load. 

There are two problems with the current behaviour;
 1. it happens _when the window closes_ so there is no feedback to the user that this has just happened
 2. it's _not needed_, clicking an extra toggle to enable this behaviour is a minimal effort intervention by the user. Having it changed without noticing is a much bigger pain.

Please either remove this function or if it was intended behaviour, add an option to turn it off.

**Comment by UnlimitedHugs** [comment]
Yeah, I've been considering to revert that particular "feature".
So, thanks for voicing your preference, that should settle it.

**Comment by UnlimitedHugs** [comment]
Implemented in [7.2.0](https://github.com/UnlimitedHugs/RimworldHugsLib/releases/tag/v7.2.0).

**Comment by FluffierThanThou** [comment]
lovely :)

**Comment by epicgodminecraft-wq** [comment]
No, just turn it off entirely.
