### ISSUE TITLE
Hugslib cannot find the file location for log output when attempting to "share logs" on Linux

### ISSUE THREAD

**Issue by Trisscar05** [UnlimitedHugs/RimworldHugsLib#73]
Creates an error window of "Log Publisher: Upload error, failed to collect data - Retry/Close".
>[HugsLib][ERR] Exception during PrepareLogData: System.IO.FileNotFoundException: Log file not found:/tmp/rimworld_log

Had a couple people post about this in main RW discord recently, seeing the same on my Ubuntu machine. *shrug*

**Comment by sTiKyt** [comment]
I just came here to create this issue xD

It's pretty easy to solve. HugsLib looks for `/tmp/rimworld_log` on Linux, but on my machine file that gets generated as log is called `rimworld_log_1000`, so full path is `/tmp/rimworld_log_1000`, solution would be just checking for this file as well, I guess?

But if you need your log to fix some issues and stuff, you can just take it manually..

**Comment by UnlimitedHugs** [comment]
A temporary fix would be to create a symbolic link at `/tmp/rimworld_log` pointing to `/tmp/rimworld_log_1000`.
Perhaps one of you could post the console command to do that for anyone else looking for a solution.

**Comment by sTiKyt** [comment]
@UnlimitedHugs i didn't think of that, but yeah, here goes command:

`ln -s /tmp/rimworld_log_1000 /tmp/rimworld_log`

**Comment by sTiKyt** [comment]
In case you don't have rimworld_log_1000 for some reason, look for any file starting with `rimworld_log` in your /tmp, (idk if that's possible, but just in case) and replace name in command i sent like this:
`ln -s /tmp/{your_file_name_goes_here} /tmp/rimworld_log`

**Comment by Trisscar05** [comment]
Nice.

**Comment by Myricaulus** [comment]
Well got the same error just now as a first time linux user. The file had the _1000 suffix. Thanks for the workaround.

**Comment by UnlimitedHugs** [comment]
Should be resolved as of 9.0.0, no more symbolic linking needed.
Tested on Mint.

**Comment by sTiKyt** [comment]
Good news

**Comment by mibli** [comment]
So running into this issue again. It seems on my arch linux running steam rimworld my logs are located in /home/user/report/rimworld_log_1000 ... linking with `ln -s /home/user/report/rimworld_log_1000 /tmp/rimworld_log` fixes the issue.
@UnlimitedHugs plz reopen
