### ISSUE TITLE
Unable to post logs to HugsLib Log Keeper

### ISSUE THREAD

**Issue by rimpy-custom** [UnlimitedHugs/RimworldHugsLib#75]
Smth going wrong with HugsLibLogKeeper. Every request to upload log ends up with "Unprocessable Entity Error". The last uploaded log is dated 05.04.2021.

My guess, smth happen with token, expired or smth. Nevertheless, we can do nothing. I hope you are still here and able to fix the issue. Thank you for your mod.

**Comment by UnlimitedHugs** [comment]
Yep, looks like it. 
I'll see if I can make some time and address this and a few other things that have piled up.

**Comment by UnlimitedHugs** [comment]
Log publisher is working again.
The problem was caused by a security issue with the account that holds the published gists.
