### ISSUE TITLE
400 Bad Request when uploading logs

### ISSUE THREAD

**Issue by kaedys** [UnlimitedHugs/RimworldHugsLib#78]
<img width="504" alt="RcSxKxMYz2" src="https://user-images.githubusercontent.com/9020449/127729274-9fc5c234-06c9-407e-9375-e72fa1deb1ac.png">
Relevant segment of the player.log:

```
[HugsLib][warn] Exception during log publishing (gist creation): System.Exception: HTTP/1.1 400 Bad Request
  at HugsLib.Utils.HugsLibUtility+<>c__DisplayClass22_0.<AwaitUnityWebResponse>b__0 () [0x000a6] in <e4b32d84f714481f906e5eea5e560e3b>:0 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

**Comment by kaedys** [comment]
Hmm, but restarting the game several times appears to have finally fixed it.  No idea what the issue was, but appears resolved.  >.>

**Comment by UnlimitedHugs** [comment]
Just some temporary issues on the side of GitHub, no worries.
