### ISSUE TITLE
Quick load does not call MemoryUtility.ClearAllMapsAndWorld()

### ISSUE THREAD

**Issue by pardeike** [UnlimitedHugs/RimworldHugsLib#80]
Which means it does not follow vanilla 1.3 standard. The original code is in
`MainMenuDrawer.DoMainMenuControls.cs for the button "SaveAndQuitToMainMenu" and also GameDataSaveLoader.LoadGame.

Because of that I have to patch HugsLib in Achtung which isn't great.

**Comment by UnlimitedHugs** [comment]
Fixed in 9.0.1. I hope my fix will play nicely with your own patch.
