### ISSUE TITLE
Noget package for 10.0.1

### ISSUE THREAD

**Issue by zlepper** [UnlimitedHugs/RimworldHugsLib#88]
Hey, great to see that 10.0.1 is out so I don't have to run my own port <3 

Is there a chance that you can publish the nuget package so it's easier to consume for other mods again? :)

**Comment by UnlimitedHugs** [comment]
Heyo. Yes, wanting to update that as well, just having some issues logging in. Will keep trying.

**Comment by UnlimitedHugs** [comment]
Success! Package update is live.
