### ISSUE TITLE
Error when aking stone blocks (1.4)

### ISSUE THREAD

**Issue by Crack-Tech** [UnlimitedHugs/RimworldHugsLib#91]
When colonist try make stone block by stone cutters table, game throw error. When cutting is end, he dont recive blocks, but try cut the same stone slub forever.
Error:
JobDriver threw exception in toil FinishRecipeAndStartStoringProduct's initAction for pawn Guillermo driver=JobDriver_DoBill (toilIndex=16) driver.job=(DoBill (Job_265) A=Thing_TableStonecutter25414 B=Thing_ChunkSlate7287 C=(113, 0, 137))
System.MissingMethodException: single RimWorld.StatExtension.GetStatValue(Verse.Thing,RimWorld.StatDef,bool)
  at (wrapper dynamic-method) Verse.GenRecipe.Verse.GenRecipe.MakeRecipeProducts_Patch1(Verse.RecipeDef,Verse.Pawn,System.Collections.Generic.List`1<Verse.Thing>,Verse.Thing,RimWorld.IBillGiver,RimWorld.Precept_ThingStyle,Verse.ThingStyleDef,System.Nullable`1<int>)
  at Verse.AI.Toils_Recipe+<>c__DisplayClass3_0.<FinishRecipeAndStartStoringProduct>b__0 () [0x0013b] in <da600864a9db4f8087fd0b640e5c28b6>:0 
  at Verse.AI.JobDriver.TryActuallyStartNextToil () [0x001b0] in <da600864a9db4f8087fd0b640e5c28b6>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.AI.JobUtility:TryStartErrorRecoverJob (Verse.Pawn,string,System.Exception,Verse.AI.JobDriver)
Verse.AI.JobDriver:TryActuallyStartNextToil ()
Verse.AI.JobDriver:ReadyForNextToil ()
Verse.AI.JobDriver:TryActuallyStartNextToil ()
Verse.AI.JobDriver:ReadyForNextToil ()
Verse.AI.Toils_Recipe/<>c__DisplayClass2_0:<DoRecipeWork>b__1 ()
Verse.AI.JobDriver:DriverTick ()
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()

**Comment by SaintBeef** [comment]
Crack-Tech, could you please include the steps to reproduce the error so it can be confirmed. 

Also, I've never experienced this error with HugsLib in my time using it. Do you have any mods which alter Stone Cutting?

**Comment by UnlimitedHugs** [comment]
Closing as likely unrelated to HugsLib.
