### ISSUE TITLE
400 Bad Request when attempting to share logs

### ISSUE THREAD

**Issue by sgtsquiggs** [UnlimitedHugs/RimworldHugsLib#92]
Apologies in advance if this is the wrong venue for this report.

Using "recommended settings" always results in 400 Bad Request.

Link to logs: https://gist.github.com/sgtsquiggs/7155a5d67b6426edf50f5fa0b1a16915

**Comment by UnlimitedHugs** [comment]
Likely a temporary issue related to GitHub gist hosting. Please feel free to reopen if the issue persists.
